/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import Personalizacion.RedondearBorde;
import Personalizacion.RenderColor;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.util.Enumeration;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author mateo
 */
public class Administrar extends javax.swing.JPanel {
    
//    int[] anchoProducto = {50, 300, 50};
    int[] anchoCategoria = {50, 600};
    String[] titulosCategoria = {"Id", "Nombre"};
    String[][] datosCategoria = {{"001", "Bebidas"}, {"002", "Bocas"}, {"003", "Entredas"}, {"004", "Plato fuerte"}, {"005", "Postre"}, {"006", "Sopas"}};
    String[] titulosProducto = {"Id", "Nombre", "Precio"};
    String[][] datosProducto = {{"001", "Pepsi", "$0.75"},
                                {"002", "Café", "$0.75"},
                                {"003","Tres leches", "$1.50"},
                                {"004", "Pastel de Chocolate", "$1.75"},
                                {"005", "Pollo asado", "$2.00"}};
    DefaultTableModel modeloCategoria;
    DefaultTableModel modeloProducto;

    /**
     * Creates new form Administrar
     */
    public Administrar() {
        initComponents();
        modeloProducto = new DefaultTableModel(datosProducto, titulosProducto);
        
        ListaCategoria();
        tblProducto.setModel(modeloProducto);
        modeloCategoria = new DefaultTableModel(datosCategoria, titulosCategoria);
//        tblCategoria.setModel(modeloCategoria);
//        personalizarComponentes(tblProducto, anchoProducto);
        personalizarComponentes(tblProducto, anchoCategoria);
//////        this.setResizable(false);
    }
    public final void personalizarComponentes(JTable tabla, int[] ancho){
        //Tabla Productos
        Enumeration<TableColumn> en = tabla.getColumnModel().getColumns();
        while (en.hasMoreElements()) {
            TableColumn tc = en.nextElement();
            tc.setCellRenderer(new RenderColor(new Color(179, 210, 238)));
        }
         tabla.setRowHeight(20);
        TableColumnModel tcm = tabla.getColumnModel();
        for (int i = 0; i < ancho.length; i++) {
            tcm.getColumn(i).setPreferredWidth(ancho[i]);
        }
    }
    public void ListaCategoria(){
        DefaultListModel modeloLista= new DefaultListModel();       
        this.lstAdminCategorias.setModel(modeloLista);        
        modeloLista.addElement("Entradas");
        modeloLista.addElement("plato Fuerte");        
        modeloLista.addElement("Sopas");
        modeloLista.addElement("Bebidas");
        modeloLista.addElement("Bocas");
        modeloLista.addElement("Postres");
        modeloLista.addElement("------------------------");  
        modeloLista.addElement("--------------"); 
        modeloLista.addElement("--------------"); 
        modeloLista.addElement("--------------"); 
        modeloLista.addElement("--------------"); 
        modeloLista.addElement("--------------"); 
        modeloLista.addElement("--------------"); 
        modeloLista.addElement("--------------"); 
        modeloLista.addElement("--------------"); 
        modeloLista.addElement("--------------"); 
        modeloLista.addElement("--------------"); 
        modeloLista.addElement("--------------"); 
        modeloLista.addElement("--------------"); 
        modeloLista.addElement("--------------"); 
        
        
       }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstAdminCategorias = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProducto = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnAdmNuevoProductos = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnAdmNuevoProductos1 = new javax.swing.JButton();

        setBackground(Color.decode("#2A3132"));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel1.setForeground(Color.decode("#90AFC5"));
        jLabel1.setText("Administrar");

        lstAdminCategorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstAdminCategoriasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstAdminCategorias);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(Color.decode("#90AFC5"));
        jLabel5.setText("Categorias");

        tblProducto.setBackground(Color.decode("#90AFC5"));
        tblProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblProducto);

        jLabel2.setForeground(Color.decode("#90AFC5"));
        jLabel2.setText("Nueva Categoria");

        btnAdmNuevoProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmNuevoProductosActionPerformed(evt);
            }
        });

        jLabel3.setForeground(Color.decode("#90AFC5"));
        jLabel3.setText("Nuevo Producto");

        btnAdmNuevoProductos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmNuevoProductos1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnAdmNuevoProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnAdmNuevoProductos1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(85, 85, 85)))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE))
                        .addGap(20, 20, 20)
                        .addComponent(btnAdmNuevoProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAdmNuevoProductos1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(44, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lstAdminCategoriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstAdminCategoriasMouseClicked
//         public void poputTable(){
    
        JPopupMenu popupMenu = new JPopupMenu ();
        
        JMenuItem menuItem1 = new JMenuItem("Modificar Categoria", new ImageIcon(getClass().getResource("/Recursos/modificarProductos.png")));
        JMenuItem menuItem2 = new JMenuItem("Eliminar Categoria", new ImageIcon(getClass().getResource("/Recursos/imprimir.png")));
//        JMenuItem menuItem3 = new JMenuItem("Modificar Cuenta", new ImageIcon(getClass().getResource("/Recursos/modificarOrden.png")));
//        JMenuItem menuItem4 = new JMenuItem("Cobrar", new ImageIcon(getClass().getResource("/Recursos/cobrar.png")));
        
        menuItem1.addActionListener((ActionEvent e) -> {            
//            MenuAgregar p = new MenuAgregar();
//            p.setVisible(true);   
        });
        
        menuItem2.addActionListener((ActionEvent e) -> {            
//            NuevaOrden nvo = new NuevaOrden();
//            nvo.setVisible(true);   
        });
        
//        menuItem4.addActionListener((ActionEvent e) -> {            
//            Cobrar co = new Cobrar();
//            co.setVisible(true);   
//        });
//        
        popupMenu.add(menuItem1);
        popupMenu.add(menuItem2);
//        popupMenu.add(menuItem3);
//        popupMenu.add(menuItem4);
        lstAdminCategorias.setComponentPopupMenu(popupMenu);
        tblProducto.setComponentPopupMenu(popupMenu);
//    }
    }//GEN-LAST:event_lstAdminCategoriasMouseClicked

    private void btnAdmNuevoProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmNuevoProductosActionPerformed
        AMProducto nuProd = new AMProducto();
        nuProd.setVisible(true);
        
    }//GEN-LAST:event_btnAdmNuevoProductosActionPerformed

    private void tblProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductoMouseClicked
        JPopupMenu popupMenu = new JPopupMenu ();
        
        JMenuItem menuItem1 = new JMenuItem("Modificar Producto", new ImageIcon(getClass().getResource("/Recursos/modificarProductos.png")));
        JMenuItem menuItem2 = new JMenuItem("Eliminar Producto", new ImageIcon(getClass().getResource("/Recursos/imprimir.png")));
//        JMenuItem menuItem3 = new JMenuItem("Modificar Cuenta", new ImageIcon(getClass().getResource("/Recursos/modificarOrden.png")));
//        JMenuItem menuItem4 = new JMenuItem("Cobrar", new ImageIcon(getClass().getResource("/Recursos/cobrar.png")));
        
        menuItem1.addActionListener((ActionEvent e) -> {            
            AMProducto p = new AMProducto();
            p.setVisible(true);   
        });
        
        menuItem2.addActionListener((ActionEvent e) -> {            
//            NuevaOrden nvo = new NuevaOrden();
//            nvo.setVisible(true);   
        });
        
//        menuItem4.addActionListener((ActionEvent e) -> {            
//            Cobrar co = new Cobrar();
//            co.setVisible(true);   
//        });
//        
        popupMenu.add(menuItem1);
        popupMenu.add(menuItem2);
//        popupMenu.add(menuItem3);
//        popupMenu.add(menuItem4);
//        lstAdminCategorias.setComponentPopupMenu(popupMenu);
        tblProducto.setComponentPopupMenu(popupMenu);
    }//GEN-LAST:event_tblProductoMouseClicked

    private void btnAdmNuevoProductos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmNuevoProductos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdmNuevoProductos1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmNuevoProductos;
    private javax.swing.JButton btnAdmNuevoProductos1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstAdminCategorias;
    private javax.swing.JTable tblProducto;
    // End of variables declaration//GEN-END:variables
}
