/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

//import com.sun.prism.paint.Color;
//import Personalizacion.RedondearBorde;
import javax.swing.UIManager;
import java.awt.Color;
import javax.swing.ImageIcon;
/**
 *
 * @author mateo
 */
public class DashBoard extends javax.swing.JFrame {
    Inicio p1;
    Administrar p2;
    Estadisticas p3;
    
    /**
     * Creates new form Principal
     */
    public DashBoard() {
        initComponents();
        setLocationRelativeTo(null);
        
        inicializarContenedor();
        
       // jFrame.setBackground(Color.decode("#F8F5F2"));
      // getContentPane().setBackground(Color.decode("#008080"));
       setIconImage(new ImageIcon(getClass().getResource("/Recursos/resbarICON_.png")).getImage());
       this.setResizable(false);
       
    }
    
    public final void inicializarContenedor(){
        p1 = new Inicio();
        p1.setSize(692, 703);
        p1.setLocation(0,0);
        
        jpContenedor.removeAll();
        jpContenedor.add(p1);
        jpContenedor.revalidate();
        jpContenedor.repaint();
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpContenedor = new javax.swing.JPanel();
        btnInicio = new javax.swing.JButton();
        btnAdministrar = new javax.swing.JButton();
        btnEstadisticas = new javax.swing.JButton();
        lblFondo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio");
        setForeground(new java.awt.Color(51, 51, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jpContenedorLayout = new javax.swing.GroupLayout(jpContenedor);
        jpContenedor.setLayout(jpContenedorLayout);
        jpContenedorLayout.setHorizontalGroup(
            jpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 692, Short.MAX_VALUE)
        );
        jpContenedorLayout.setVerticalGroup(
            jpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 703, Short.MAX_VALUE)
        );

        getContentPane().add(jpContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 53, -1, 703));

        btnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/inicio.jpg"))); // NOI18N
        btnInicio.setFocusPainted(false);
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        getContentPane().add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 296, 99));

        btnAdministrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/administracion.jpg"))); // NOI18N
        btnAdministrar.setFocusPainted(false);
        btnAdministrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdministrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 288, 293, 98));

        btnEstadisticas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/estadisticas.jpg"))); // NOI18N
        btnEstadisticas.setFocusPainted(false);
        btnEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadisticasActionPerformed(evt);
            }
        });
        getContentPane().add(btnEstadisticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 468, 293, 98));

        lblFondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/34_Spicy_Neutrals01.png"))); // NOI18N
        getContentPane().add(lblFondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        p1 = new Inicio();
        p1.setSize(692, 703);
        p1.setLocation(0,0);
        
        jpContenedor.removeAll();
        jpContenedor.add(p1);
        jpContenedor.revalidate();
        jpContenedor.repaint();
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnAdministrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministrarActionPerformed
        p2 = new Administrar();
        p2.setSize(692, 703);
        p2.setLocation(0,0);
        
        jpContenedor.removeAll();
        jpContenedor.add(p2);
        jpContenedor.revalidate();
        jpContenedor.repaint();
    }//GEN-LAST:event_btnAdministrarActionPerformed

    private void btnEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadisticasActionPerformed
        p3 = new Estadisticas();
        p3.setSize(692, 703);
        p3.setLocation(0,0);
        
        jpContenedor.removeAll();
        jpContenedor.add(p3);
        jpContenedor.revalidate();
        jpContenedor.repaint();
    }//GEN-LAST:event_btnEstadisticasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");   
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnAdministrar;
    private javax.swing.JButton btnEstadisticas;
    private javax.swing.JButton btnInicio;
    public static javax.swing.JPanel jpContenedor;
    private javax.swing.JLabel lblFondo1;
    // End of variables declaration//GEN-END:variables
}
